//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCSs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentFile
    {
        public long AttachmentFileId { get; set; }
        public string Link { get; set; }
        public string FileName { get; set; }
        public long CandidateId { get; set; }
    }
}
