//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCSs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public long CandidateId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public bool Genger { get; set; }
        public string DOB { get; set; }
        public string JobTitle { get; set; }
        public string JobLevel { get; set; }
        public long ClientId { get; set; }
        public long RecruiterId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime LastUpdateReportTime { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public string PictureLink { get; set; }
        public string IssuranceNumber { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.DateTime> IDDate { get; set; }
        public string IDSupply { get; set; }
        public long UserLoginId { get; set; }
    }
}
