//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCSs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationInfo
    {
        public long EducationInfoId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime StopDate { get; set; }
        public string OrganizationName { get; set; }
        public string Major { get; set; }
        public string CheckingStatus { get; set; }
        public Nullable<System.DateTime> CheckingTime { get; set; }
        public bool IsChecked { get; set; }
    }
}
