//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCSs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruiter
    {
        public long RecruiterId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public long ClientId { get; set; }
        public Nullable<long> SpecialistId { get; set; }
        public long UserLoginId { get; set; }
    }
}
