//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCSs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceInfo
    {
        public long ReferenceInfoId { get; set; }
        public string FullName { get; set; }
        public string RelationShip { get; set; }
        public string JobTitle { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Note { get; set; }
        public string CheckingStatus { get; set; }
        public Nullable<System.DateTime> CheckingTime { get; set; }
        public long CompanyInfoId { get; set; }
    }
}
