//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCSs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificationLog
    {
        public long VerificationLogId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int TypeOfLog { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<long> CompanyInfoId { get; set; }
        public Nullable<long> ReferenceInfoId { get; set; }
        public Nullable<long> EducationInfoId { get; set; }
        public Nullable<long> SpecialistId { get; set; }
    }
}
